name: goldengoose
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0

  # Error Handling & Logging
  logger: ^2.0.2+1

  # Network & API
  dio: ^5.4.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Serialization & Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_messaging: ^15.2.6

  # Google Services
  google_sign_in: ^6.2.1
  google_mlkit_text_recognition: ^0.15.0

  # Payments
  flutter_stripe: ^11.5.0

  # Device & Platform
  cupertino_icons: ^1.0.2
  meta: ^1.9.1
  connectivity_plus: ^6.1.4
  camera: ^0.11.1
  torch_light: ^1.1.0
  image_picker: ^1.0.7
  geolocator: ^14.0.0
  flutter_blue: ^0.8.0
  flutter_compass: ^0.8.1
  local_auth: ^2.1.7
  flutter_secure_storage: ^10.0.0-beta.4
  device_info_plus: ^11.4.0
  permission_handler: ^12.0.0+1

  # Localization
  easy_localization: ^3.0.3

  http: ^1.1.0

dev_dependencies:
  # Flutter Testing
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # Testing & Mocking
  mockito: ^5.4.2  # Legacy, prefer mocktail
  mocktail: ^1.0.3  # Preferred for Dart 3+

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
